version: '2'
services:

    gs:
        build: ./geoserver
        ports:
            - "8081:8080"
        links:
            - postgis
        depends_on:
            - "postgis"
        command: ["./wait-for-it.sh", "postgis:5432", "-t", "120", "--", "/opt/geoserver/bin/startup.sh"]

    tomcat:
        build: ./ogp-harvester        
        ports:
            - "8082:8080"
        links:
            - postgis
        volumes:
         - ./webapps:/usr/local/tomcat/webapps/
        depends_on:
            - "postgis"
        command: ["/usr/local/tomcat/wait-for-it.sh", "postgis:5432", "-t", "120", "--", "catalina.sh run"]

    postgis:
        build: ./postgis
        ports:
            - "5433:5432"
        environment:
              - POSTGRES_USER=ogpharvester
              - POSTGRES_PASSWORD=ogpharvester

    solr:
        image: solr:6.3.0
        ports:
            - "8983:8983"
        command: solr-create -c ogp

    data-ingest:
        build: ./data-ingest        
        ports:
            - "8083:8080"
        depends_on:
            - "gs"
        links:
            - gs

