version: '2'
services:

    gs:
        image: winsent/geoserver:2.10
        ports:
            - "8081:8080"
        links:
            - postgis
        volumes:
            - ./data:/tmp

    tomcat:
        image: tomcat:8-jre8-alpine
        ports:
            - "8082:8080"
        links:
            - postgis
        volumes:
         - ./webapps:/usr/local/tomcat/webapps/

    postgis:
        image: mdillon/postgis:9.6
        ports:
            - "5432:5432"
        environment:
              - POSTGRES_USER=ogpharvester
              - POSTGRES_PASSWORD=ogpharvester

    solr:
        image: solr:6.3.0
        ports:
            - "8983:8983"
        command: solr-create -c ogp

